-- Guru Parampara Data
DELETE FROM guru_parampara;
INSERT INTO guru_parampara (id, name, order_index, ashrama_guru, ashrama_shishya, period, peetarohana, aaradhane, vrindavana_location, vrindavana_map_link, vrindavana_lat, vrindavana_long, ashrama_guru_id, ashrama_shishya_id, description) VALUES (1, 'Sri Vishnu Theertha', 1, 'Sri Madhvacharya', 'Sri Vyasa Theertha', '13th Century', 'Data Unavailable', 'Margashirsha Krishna Trayodashi', 'Kumaradri Hills (Kukke)', NULL, 12.663076230690404, 75.6602088427549, NULL, 2, 'Vishnu Theertha, the younger brother and preeminent disciple of Sri Madhvacharya, is revered as the personification of Vairagya (detachment). Following a period of devoted service to his parents, he sought asceticism (Sanyasa) from Madhvacharya. His spiritual rigor was unparalleled; he performed intense austerities on the Harishchandra and Kumara mountains, sustaining himself on minimal offerings while achieving profound meditative realizations.

An accomplished scholar, Vishnu Theertha authored foundational works such as the Samnyasapaddhati. He established a spiritual lineage through his disciples, Vyasa Theertha and Aniruddha Theertha, which evolved into the prestigious Sode Vadiraja and Subrahmanya Mathas. Tradition maintains that he remains in a state of living penance in the Western Ghats. It is prophesied that he will eventually reappear to recover the Sarvamula texts and re-establish the Dvaita philosophy.

Regarded as one of the Ruju deities, Vishnu Theertha’s life represents the pinnacle of spiritual discipline. His legacy is preserved through the worship of the Bhuvaraha and Hayagriva icons, symbolizing the continuity of his divine authority.');
INSERT INTO guru_parampara (id, name, order_index, ashrama_guru, ashrama_shishya, period, peetarohana, aaradhane, vrindavana_location, vrindavana_map_link, vrindavana_lat, vrindavana_long, ashrama_guru_id, ashrama_shishya_id, description) VALUES (2, 'Sri Vyasa Theertha', 2, 'Sri Vishnu Theertha', 'Sri Vedya Theertha', 'Upto 1327 CE', 'Data Unavailable', 'Data Unavailable', 'Location Unrecorded', NULL, NULL, NULL, 1, 3, 'Sri Vyasa Theertha, the direct disciple of Sri Vishnu Theertha, was an eminent scholar and distinguished poet within the Madhva lineage. Celebrated for his profound intellect and sagely demeanor, he was regarded with parental affection by both Sri Madhvacharya and Sri Vishnu Theertha, receiving their deepest spiritual blessings.

His contribution to the tradition was marked by a rare synthesis of scholastic excellence and poetic mastery, playing a vital role in the intellectual expansion of the Dvaita school. Beyond his academic prowess, he was a virtuous administrator of the hierarchy, conducting the worship of its sacred icons with immense devotion.

Although historical records suggest he was a prolific author, his literary works have not survived to the present day. Sri Vyasa Theertha entered his Vrindavana in 1327 CE, leaving behind a legacy of piety and spiritual erudition.');
INSERT INTO guru_parampara (id, name, order_index, ashrama_guru, ashrama_shishya, period, peetarohana, aaradhane, vrindavana_location, vrindavana_map_link, vrindavana_lat, vrindavana_long, ashrama_guru_id, ashrama_shishya_id, description) VALUES (3, 'Sri Vedya Theertha', 3, 'Sri Vyasa Theertha', 'Sri Vedagarbha Theertha', '1327-1336 CE', 'c. 1327 CE', 'Data Unavailable', 'Location Unrecorded', NULL, NULL, NULL, 2, 4, 'Having received Sanyasashrama from Sri Vyasa Theertha, Sri Vedya Theertha was a distinguished scholar who dedicated his life to the rigorous study and propagation of the Shastras. Under the guidance of his preceptor, he maintained a high standard of daily rituals and conducted the worship of the lineage’s sacred icons with great solemnity.

As a compassionate teacher, he traveled extensively on pilgrimages, offering spiritual counsel to the faithful and guiding seekers toward liberation from worldly anxieties. His tenure as the head of the Sode lineage lasted nine years, during which he significantly strengthened the intellectual and devotional foundations of the Matha. Sri Vedya Theertha entered Vrindavana in 1336 CE');
INSERT INTO guru_parampara (id, name, order_index, ashrama_guru, ashrama_shishya, period, peetarohana, aaradhane, vrindavana_location, vrindavana_map_link, vrindavana_lat, vrindavana_long, ashrama_guru_id, ashrama_shishya_id, description) VALUES (4, 'Sri Vedagarbha Theertha', 4, 'Sri Vedya Theertha', 'Sri Varesha Theertha', '1336-1346', 'c. 1336 CE', 'Data Unavailable', 'Location Unrecorded', NULL, NULL, NULL, 3, 5, 'Sri Vedagarbha Theertha was renowned for his profound mastery of Mantra-shastra and his deep insight into the esoteric secrets of sacred chants. Through his rigorous spiritual practice, he attained Siddhi (divine fulfillment), which he utilized compassionately to alleviate the suffering of the distressed.

His reputation was built upon a steadfast commitment to the prescribed Vedic norms and an unwavering dedication to his spiritual duties. Throughout his ten-year tenure as the head of the Sode lineage, he served as a pillar of stability and popularity within the community. Sri Vedagarbha Theertha entered Vrindavana in 1346 CE, concluding a decade of influential spiritual leadership.');
INSERT INTO guru_parampara (id, name, order_index, ashrama_guru, ashrama_shishya, period, peetarohana, aaradhane, vrindavana_location, vrindavana_map_link, vrindavana_lat, vrindavana_long, ashrama_guru_id, ashrama_shishya_id, description) VALUES (5, 'Sri Varesha Theertha', 5, 'Sri Vedagarbha Theertha', 'Sri Vamana Theertha', '1346-1354 CE', 'c. 1346 CE', 'Data Unavailable', 'Location Unrecorded', NULL, NULL, NULL, 4, 6, 'Sri Varesha Theertha was a profound scholar distinguished by his absolute mastery of the Sarvamula—the foundational works of Sri Madhvacharya. His erudition was characterized by a rare mnemonic feat; having memorized these complex texts in their entirety, he was able to deliver fluent and authoritative lectures that placed the Dvaita Siddhanta on a remarkably firm intellectual footing.

Throughout his eight-year tenure, he traveled extensively to disseminate the true essence of the Shastras to the devout. His mission was defined by the propagation of Vedantic truths through direct, accessible discourse. Sri Varesha Theertha entered Vrindavana in 1354 CE, leaving a legacy of academic rigor and missionary zeal.');
INSERT INTO guru_parampara (id, name, order_index, ashrama_guru, ashrama_shishya, period, peetarohana, aaradhane, vrindavana_location, vrindavana_map_link, vrindavana_lat, vrindavana_long, ashrama_guru_id, ashrama_shishya_id, description) VALUES (6, 'Sri Vamana Theertha', 6, 'Sri Varesha Theertha', 'Sri Vasudeva Theertha', '1354-1362 CE', 'c. 1354 CE', 'Data Unavailable', 'Location Unrecorded', NULL, NULL, NULL, 5, 7, 'Upon receiving Sanyasashrama , Sri Vamana Theertha embarked on extensive pilgrimages to various sacred centers, accompanied by a devoted retinue. He was particularly distinguished by his profound reverence for the Bhagavata Purana, a text that became the focal point of his spiritual ministry.

Renowned for his oratorical skills, he frequently delivered discourses on the Bhagavata, where his melodic recitation of the Shlokas was said to immerse his audience in a deep stream of devotion. In a notable departure from common practice, Sri Vamana Theertha nominated his successor despite not yet reaching an advanced age. He held the tenure seat for a period of eight years before entering Vrindavana in 1362 CE');
INSERT INTO guru_parampara (id, name, order_index, ashrama_guru, ashrama_shishya, period, peetarohana, aaradhane, vrindavana_location, vrindavana_map_link, vrindavana_lat, vrindavana_long, ashrama_guru_id, ashrama_shishya_id, description) VALUES (7, 'Sri Vasudeva Theertha', 7, 'Sri Vamana Theertha', 'Sri Vedavyasa Theertha', '1362-1369 CE', 'c. 1362 CE', 'Data Unavailable', 'Location Unrecorded', NULL, NULL, NULL, 6, 8, 'Upholding the rigorous traditions of worship and spiritual discipline, Sri Vasudeva Theertha distinguished himself through his profound dedication to the Brahmasutra Bhashya of Sri Madhvacharya. He revered this foundational text as the very living presence of his preceptor, and his mastery was such that he had committed the entire work to memory.

Unlike many of his predecessors who traveled extensively, Sri Vasudeva Theertha preferred a life of contemplative stability. He spent the majority of his tenure in the sacred presence of Lord Krishna at Udupi, where he focused on delivering insightful lectures and teaching the deeper philosophical nuances of the Bhashya. After a seven-year pontificate, he entered Vrindavana in 1369 CE');
INSERT INTO guru_parampara (id, name, order_index, ashrama_guru, ashrama_shishya, period, peetarohana, aaradhane, vrindavana_location, vrindavana_map_link, vrindavana_lat, vrindavana_long, ashrama_guru_id, ashrama_shishya_id, description) VALUES (8, 'Sri Vedavyasa Theertha', 8, 'Sri Vasudeva Theertha', 'Sri Varaha Theertha', '1369-1377 CE', 'c. 1369 CE', 'Ashwayuja Shudha Chaturthi', 'Location Unrecorded', NULL, NULL, NULL, 7, 9, 'Sri Vedavyasa Theertha was a matchless scholar and a formidable debater, renowned for his dominance in theological disputation. His intellectual prowess was particularly evident in his ability to spontaneously quote from his opponents own texts while refuting their tenets. This mastery extended beyond his own tradition, as he possessed a comprehensive command of the Shankarabhashya and other non-Dualist works.

Attributing his success to the divine grace of Hari-Vayu-Guru, he excelled in both public debates and scholarly discourses. His tenure as the head of the Sode lineage lasted eight years, during which he significantly bolstered the intellectual defenses of the school. Sri Vedavyasa Theertha entered Vrindavana in 1377 CE');
INSERT INTO guru_parampara (id, name, order_index, ashrama_guru, ashrama_shishya, period, peetarohana, aaradhane, vrindavana_location, vrindavana_map_link, vrindavana_lat, vrindavana_long, ashrama_guru_id, ashrama_shishya_id, description) VALUES (9, 'Sri Varaha Theertha', 9, 'Sri Vedavyasa Theertha', 'Sri Vedatma Theertha', '1377-1386 CE', 'c. 1377 CE', 'Data Unavailable', 'Location Unrecorded', NULL, NULL, NULL, 8, 10, 'Sri Varaha Theertha, the direct disciple of Sri Vedavyasa Theertha, was characterized by his profound inclination toward Japa (meditative recitation) and Tapa (austere penance). An advanced practitioner of Yoga, he possessed significant spiritual powers and spent much of his life in solitary meditation, reflecting the temperament of a true Yogin.

Preferring the quietude of secluded environments, Sri Varaha Theertha dedicated his spiritual merits to the welfare of his faithful devotees. In a strategic move for the continuity of the lineage, he nominated and empowered his successor while still in middle age. His pontificate lasted nine years, concluding with his entry into Vrindavana in 1386 CE');
INSERT INTO guru_parampara (id, name, order_index, ashrama_guru, ashrama_shishya, period, peetarohana, aaradhane, vrindavana_location, vrindavana_map_link, vrindavana_lat, vrindavana_long, ashrama_guru_id, ashrama_shishya_id, description) VALUES (10, 'Sri Vedatma Theertha', 10, 'Sri Varaha Theertha', 'Sri Vishwavandya Theertha I', '1386-1422 CE', 'c. 1386 CE', 'Data Unavailable', 'Location Unrecorded', NULL, NULL, NULL, 9, 11, 'During the late 14th century, Sri Vedatma Theertha emerged as a prominent figure in the lineage of Sri Vishnu Theertha. Renowned for his comprehensive mastery of the Vedas and Vedangas, he was also a distinguished poet whose scholarly contributions were marked by exceptional grammatical precision and aesthetic grace.

While tradition suggests he was a prolific author, his most significant extant work is Kavikarnamrutam, a scholarly commentary on the Vayustuti by Trivikrama Panditacharya. This work is highly regarded for its poetic sophistication and linguistic depth. Additionally, historical accounts attribute a commentary on Sri Madhvacharya’s Nakhastuti to him. Sri Vedatma Theertha presided over the tenure seat for twelve years, significantly enriching the intellectual heritage of the Matha before entering Vrindavana in 1398 CE');
INSERT INTO guru_parampara (id, name, order_index, ashrama_guru, ashrama_shishya, period, peetarohana, aaradhane, vrindavana_location, vrindavana_map_link, vrindavana_lat, vrindavana_long, ashrama_guru_id, ashrama_shishya_id, description) VALUES (11, 'Sri Vishwavandya Theertha I', 11, 'Sri Vedatma Theertha', 'Sri Ratnagarbha Theertha', 'Early 15th Cent.', 'Data Unavailable', 'Data Unavailable', 'Location Unrecorded', NULL, NULL, NULL, 10, 12, 'Sri Vishwavandya Theertha was a multifaceted personality whose tenure as the head of the lineage was marked by both spiritual fruitfulness and practical wisdom. He possessed a rare synthesis of profound Shastric erudition and a sophisticated understanding of worldly affairs, making him an exceptionally capable leader.

A master of diverse arts and sciences, he was a formidable presence in the scholarly arena. During theological debates, he was renowned for his "stock and sample" replies—precise, instantaneous, and devastatingly effective arguments that consistently silenced his opponents. His intellectual agility and authoritative discourse left audiences stunned and further solidified the prestige of the Sode lineage. Sri Vishwavandya Theertha presided over the tenure seat for twenty-four years, entering Vrindavana in 1422 CE');
INSERT INTO guru_parampara (id, name, order_index, ashrama_guru, ashrama_shishya, period, peetarohana, aaradhane, vrindavana_location, vrindavana_map_link, vrindavana_lat, vrindavana_long, ashrama_guru_id, ashrama_shishya_id, description) VALUES (12, 'Sri Ratnagarbha Theertha', 12, 'Sri Vishwavandya Theertha I', 'Sri Vedanga Theertha', 'Mid 15th Cent.', 'Data Unavailable', 'Data Unavailable', 'Narala (near Mangalore)', 'https://maps.app.goo.gl/L6CzTBKzKsn1cRrz5', 12.963322327053016, 74.96645196906792, 11, 13, 'Sri Ratnagarbha Theertha, the successor of Sri Vishwavandya Theertha, was an extraordinary scholar and mystic whose life was defined by profound Yogic feats and divine interventions. Residing in the secluded region of Narala, he performed severe penances, including the miraculous ability to levitate over a hundred feet into the air during meditation. His spiritual aura was so potent that natural predators in the surrounding forest reportedly abandoned their mutual animosity.

A pivotal historical moment involves his protection of a displaced king from the Chowta dynasty. Through intense meditation on Lord Bhuvaraha, Sri Ratnagarbha Theertha granted the king a divine vision and invoked the prtection of the Lord to defeat the enemies of the king. Furthermore, he miraculously solved a regional water scarcity by invoking Lord Varaha, whose movement created a perennial spring that remains visible today. Narala is also significant as the birthplace of the prominent deity Sri Bhutaraja (known locally as Naralattaya).

Sri Ratnagarbha Theertha is credited with a commentary on the Mahabharata Tatparya Nirnaya. Uniquely, he is said to have cast off his mortal coil through Yogic power in Narala prior to the passing of his Guru in 1422 CE');
INSERT INTO guru_parampara (id, name, order_index, ashrama_guru, ashrama_shishya, period, peetarohana, aaradhane, vrindavana_location, vrindavana_map_link, vrindavana_lat, vrindavana_long, ashrama_guru_id, ashrama_shishya_id, description) VALUES (13, 'Sri Vedanga Theertha', 13, 'Sri Ratnagarbha Theertha', 'Sri Vidyapati Theertha', '1422-1441 CE', 'c. 1422 CE', 'Data Unavailable', 'Beelagi (Siddapura)', NULL, NULL, NULL, 12, 14, 'In the lineage of Sri Vishnu Theertha, Sri Vedanga Theertha emerged as a prolific author and intellectual leader prior to the era of Sri Vadiraja Theertha. Having received Sanyasashrama from Sri Vishwavandya Theertha, he attained profound mastery over the Vedas, Vedangas, and Vedanta. His tenure was characterized by a "towering fame," as he successfully expanded the influence of the Matha through continuous teaching and the composition of numerous commentaries and independent philosophical works.

Even while on pilgrimage, Vedanga Theertha remained committed to the pedagogical tradition, educating disciples in the sacred lores. He entered Vrindavana in 1441 CE at Bilagi, situated on the banks of the Soma (Aghanashini) River. This site later gained further significance when Sri Vadiraja Theertha interred a complete set of his own works there, consecrating the spot with icons of Lord Vedavyasa, Hanuman, and Garuda.');
INSERT INTO guru_parampara (id, name, order_index, ashrama_guru, ashrama_shishya, period, peetarohana, aaradhane, vrindavana_location, vrindavana_map_link, vrindavana_lat, vrindavana_long, ashrama_guru_id, ashrama_shishya_id, description) VALUES (14, 'Sri Vidyapati Theertha', 14, 'Sri Vedanga Theertha', 'Sri Vishwavandya Theertha II', '1441-1449 CE', 'c. 1441 CE', 'Data Unavailable', 'Location Unrecorded', NULL, NULL, NULL, 13, 15, 'Sri Vidyapati Theertha, a devoted disciple of Sri Vedanga Theertha, was highly esteemed for his piety and virtuous conduct. He chose to spend the majority of his life in the sacred town of Udupi, maintaining a deep connection to the holy presence of Lord Krishna.

His spiritual practice was characterized by constant immersion in the scriptures; he was known for his unique habit of reciting and chanting sacred texts even while walking, turning every moment into an act of worship. Sri Vidyapati Theertha presided over the lineage for eight years, upholding the spiritual standards of the tradition  before entering Vrindavana in 1449 CE');
INSERT INTO guru_parampara (id, name, order_index, ashrama_guru, ashrama_shishya, period, peetarohana, aaradhane, vrindavana_location, vrindavana_map_link, vrindavana_lat, vrindavana_long, ashrama_guru_id, ashrama_shishya_id, description) VALUES (15, 'Sri Vishwavandya Theertha II', 15, 'Sri Vidyapati Theertha', 'Sri Vishwa Theertha', '1449-1458 CE', 'c. 1458 CE', 'Data Unavailable', 'Location Unrecorded', NULL, NULL, NULL, 14, 16, 'Sri Vishwandya Theertha, the successor to Sri Vidyapati Theertha, was a renowned mystic endowed with the Ashta Siddhis—extraordinary yogic powers such as Anima (minuteness), Mahima (vastness), and Garima (heaviness). Driven by a compassionate concern for the faithful, he was known for providing immediate spiritual remedies to those in distress.

A fearless ascetic, he often wandered alone in solitary contemplation. His spiritual authority was most notably demonstrated during a Paryaya festival in Udupi, where he used his mystic powers to effectively neutralize the disruptive attempts of his detractors. Sri Vishwandya Theertha presided over the lineage for nine years, entering Vrindavana in 1458 CE');
INSERT INTO guru_parampara (id, name, order_index, ashrama_guru, ashrama_shishya, period, peetarohana, aaradhane, vrindavana_location, vrindavana_map_link, vrindavana_lat, vrindavana_long, ashrama_guru_id, ashrama_shishya_id, description) VALUES (16, 'Sri Vishwa Theertha', 16, 'Sri Vishwavandya Theertha II', 'Sri Vittala Theertha', '1458-1466 CE', 'c. 1466 CE', 'Data Unavailable', 'Location Unrecorded', NULL, NULL, NULL, 15, 17, 'Sri Vishwa Theertha was a dedicated custodian of the Parampara, ensuring that the prescribed norms and rituals of the lineage were executed with flawless precision. He was particularly known for his missionary zeal, working on a "war footing" to propagate the doctrines of Dvaita Siddhanta and strengthen the philosophical foundation of the Matha.

His life was a testament to disciplined observance and tireless advocacy for Sri Madhvacharya’s teachings. After a fruitful eight-year tenure as the head of the Sode lineage, he attained the holy feet of the Lord and entered Vrindavana in 1466 CE');
INSERT INTO guru_parampara (id, name, order_index, ashrama_guru, ashrama_shishya, period, peetarohana, aaradhane, vrindavana_location, vrindavana_map_link, vrindavana_lat, vrindavana_long, ashrama_guru_id, ashrama_shishya_id, description) VALUES (17, 'Sri Vittala Theertha', 17, 'Sri Vishwa Theertha', 'Sri Varadaraja Theertha I', '1466-1473 CE', 'c. 1466 CE', 'Data Unavailable', 'Location Unrecorded', NULL, NULL, NULL, 16, 18, 'Sri Vitthala Theertha was a saintly ascetic who favored the spiritual tranquility of Madhyavata Matha, where he resided for much of his tenure. His life was centered on the devoted worship of Lord Vedavyasa, and tradition records that his pure dedication earned him profound divine grace.

His seven-year period of leadership was marked by a deep internal focus on spiritual realization and the maintenance of the sacred traditions of the lineage . Historically, his tenure is of great significance as it directly precedes the arrival of one of the most towering figures in the Madhva tradition. Sri Vitthala Theertha entered Vrindavana in 1473 CE');
INSERT INTO guru_parampara (id, name, order_index, ashrama_guru, ashrama_shishya, period, peetarohana, aaradhane, vrindavana_location, vrindavana_map_link, vrindavana_lat, vrindavana_long, ashrama_guru_id, ashrama_shishya_id, description) VALUES (18, 'Sri Varadaraja Theertha I', 18, 'Sri Vittala Theertha', 'Sri Vageesha Theertha', '1473-1481 CE', 'c. 1473 CE', 'Data Unavailable', 'Kumbhasi', 'https://maps.google.com/?q=13.568916,74.702364', 13.568824374112861, 74.70223029224076, 17, 19, 'Sri Varadaraja Theertha, the eighteenth pontiff in the lineage of Sri Vishnu Theertha, was a renowned pilgrim and scholar who significantly developed the infrastructure of the Matha. He is credited with the first renovation of the Kumbhasi Matha, establishing it as a key spiritual center.

An expert in the Bhagavad Gita, he engaged in successful theological debates across the country. He was also revered for his mystical healing powers, famously curing a Brahmin named Narahari of a terminal illness and miraculously granting the power of speech and oratory to a mute celibate. Sri Varadaraja Theertha presided over the lineage for eight years before entering Vrindavana in 1481 CE His tomb is located adjacent to the Harihareshwara Temple in Kumbhasi.');
INSERT INTO guru_parampara (id, name, order_index, ashrama_guru, ashrama_shishya, period, peetarohana, aaradhane, vrindavana_location, vrindavana_map_link, vrindavana_lat, vrindavana_long, ashrama_guru_id, ashrama_shishya_id, description) VALUES (19, 'Sri Vageesha Theertha', 19, 'Sri Varadaraja Theertha I', 'Sri Vadiraja Theertha', '1481-1518 CE', 'c. 1481 CE', 'Chaitra Krishna Dwitiya', 'Udupi', NULL, 13.3416944115392, 74.75298113858852, 18, 20, 'Sri Vagisha Theertha, the nineteenth pontiff, holds a distinguished place in history as the Ashramaguru (preceptor) of the legendary Sri Vadiraja Theertha. A saint-scholar of profound intuitive vision, he resided primarily at Kumbhasi Matha, where he balanced rigorous austerities with the dissemination of sacred knowledge.

His most significant spiritual contribution was his role in the incarnation of Sri Vadiraja Theertha. Through divine communion with Lord Varaha, Vagisha Theertha foretold the birth of the Latavya Ruju deity to the devotee couple, Ramacharya and Gauri Devi. Following divine instructions, he initiated the young prodigy into the ascetic order, naming him Vadiraja Theertha.

Renowned for his mastery over time (Trikala-jnana), he offered spiritual relief to devotees through the power of consecrated Mantrakshata. He spent his final years in Udupi, dedicated to pedagogical pursuits. Sri Vagisha Theertha entered Vrindavana in 1518 CE after a transformative 37-year tenure. His shrine remains a center of miracles, famously granting the blessing of progeny to the Kuppannatantri couple, who later adorned the Vrindavana with a brass Kavacha (armor) in gratitude.');
INSERT INTO guru_parampara (id, name, order_index, ashrama_guru, ashrama_shishya, period, peetarohana, aaradhane, vrindavana_location, vrindavana_map_link, vrindavana_lat, vrindavana_long, ashrama_guru_id, ashrama_shishya_id, description) VALUES (20, 'Sri Vadiraja Theertha', 20, 'Sri Vageesha Theertha', 'Sri Vedavedya Theertha', '1480–1600 CE', 'c. 1488 (Sanyasa)', 'Phalguna Krishna Tritiya', 'Sode (Pancha Vrindavana)', 'https://maps.app.goo.gl/QVGRLSPLX9wtmfQt9', 14.734674684081776, 74.77885236443097, 19, 21 , 'Sri Vadiraja Theertha stands as the preeminent "crest jewel" of the lineage established by Sri Vishnu Theertha. Born in 1481 CE as Varaha to Ramacharya and Gauri, his birth was a divine gift facilitated by the blessings of Lord Varaha and his preceptor, Sri Vagisha Theertha. Showing early spiritual maturity, he was initiated into Sanyasashrama at the age of seven and given the name Vadiraja Theertha, symbolizing his prowess as a "lion among debaters."

After mastering the Shastras under Vidyanidhi and Vagisha Theertha, he embarked on extensive pilgrimages across India. These travels culminated in the composition of the  Theerthaprabandha, a unique Sanskrit travelogue detailing India’s sacred geography.

Sri Vadiraja’s life was defined by profound miracles and scholarly milestones. He was the only saint after Madhvacharya to visit Urdhvabadari, where, at the instruction of Lord Vedavyasa, he authored the Lakshalankara (a commentary on the Mahabharata). He also secured the Vyasamushti for the Madhyavata Matha and famously received the icon of Lord Hayagriva. His unique devotion included offering a special sweet dish (Hayagriva Maddi) to the Lord, who would personally accept the offering in a divine form.');
INSERT INTO guru_parampara (id, name, order_index, ashrama_guru, ashrama_shishya, period, peetarohana, aaradhane, vrindavana_location, vrindavana_map_link, vrindavana_lat, vrindavana_long, ashrama_guru_id, ashrama_shishya_id, description) VALUES (21, 'Sri Vedavedya Theertha', 21, 'Sri Vadiraja Theertha', 'Sri Vidyanidhi Theertha', '1530–1616 CE', 'c. 1600 CE', 'Kartika Krishna Trayodashi', 'Sode', 'https://maps.app.goo.gl/QVGRLSPLX9wtmfQt9', 14.734674684081776, 74.77885236443097, 20, 22, 'Sri Vedavedya Theertha, the direct disciple of Sri Vadiraja, was initiated into the ascetic order in 1540. A scholar of immense spiritual caliber, he is uniquely identified in the Vrindavanakhyana as the Gavya Ruju deity, possessing the Siddhi of the Vadiraja Mantra. His tenure was marked by profound devotion and administrative milestones, including the performance of two biennial Paryayas in Udupi. During his second term (1612–1614), he renovated the Sri Krishna Temple with a stone structure and a copper roof, a historical fact verified by a 1613 stone inscription recording a land grant from King Venkatappa Nayaka of Ikkeri.

Recognizing the divine status of his preceptor, Sri Vedavedya Theertha introduced the Samapuja system, where Sri Vadiraja is worshipped alongside the incarnations of Vayu. He also instituted the daily Paraku proclamation, a tradition of chanting Vadiraja’s titles of praise during evening worship that remains in practice today. Tradition records a miraculous event where Vedavedya was granted a physical vision of his master at Sode, facilitated by Sri Bhutaraja. He presided over the lineage for 15 years before entering his holy Vrindavana at Sonda in 1616 CE, where his shrine rests beside that of his Guru.');
INSERT INTO guru_parampara (id, name, order_index, ashrama_guru, ashrama_shishya, period, peetarohana, aaradhane, vrindavana_location, vrindavana_map_link, vrindavana_lat, vrindavana_long, ashrama_guru_id, ashrama_shishya_id, description) VALUES (22, 'Sri Vidyanidhi Theertha', 22, 'Sri Vedavedya Theertha', 'Sri Vedanidhi Theertha', 'Upto 1598', 'Data Unavailable', 'Data Unavailable', 'Kumbhasi', 'https://maps.google.com/?q=13.568916,74.702364', 13.568824374112861, 74.70223029224076, 21, 23, 'Sri Vidyanidhi Theertha was initiated into Sanyasashrama by Sri Vedavedya Theertha in 1585 and pursued his advanced studies directly under the legendary Sri Vadiraja. A gifted orator and a trusted assistant to his preceptor, he played a crucial role during the first biennial Paryaya of 1596–1597. However, his academic journey met a sudden turning point when an irrelevant question during a lesson led Sri Vadiraja to reveal that Vidyanidhi faced a shortened lifespan. Following his master’s advice, he embarked on a final pilgrimage before settling at Kumbhasi Matha, where he entered his holy Vrindavana in 1598.

Throughout his thirteen years of ascetic life, Sri Vidyanidhi Theertha remained a significant figure, yet he stands as the only pontiff in this specific lineage who did not perform a Paryaya in Udupi. Anticipating his early departure, he followed Sri Vadiraja’s instructions to nominate a successor, Sri Vidyanidhi Theertha, in 1593. His tenure coincided with a unique historical period where four different pontiffs were present within the hierarchy between 1593 and 1598. Today, his Vrindavana is situated at Kumbhasi, resting beside the Vrindavana of Sri Varadaraja Theertha I.');
INSERT INTO guru_parampara (id, name, order_index, ashrama_guru, ashrama_shishya, period, peetarohana, aaradhane, vrindavana_location, vrindavana_map_link, vrindavana_lat, vrindavana_long, ashrama_guru_id, ashrama_shishya_id, description) VALUES (23, 'Sri Vedanidhi Theertha', 23, 'Sri Vidyanidhi Theertha', 'Sri Varadaraja Theertha II', 'Upto 1648 CE', 'Data Unavailable', 'Data Unavailable', 'Sode', 'https://maps.app.goo.gl/QVGRLSPLX9wtmfQt9', 14.734674684081776, 74.77885236443097, 22, 24, 'Sri Vedanidhi Theertha, a prominent disciple in the lineage of Sri Vadiraja, was initiated into Sanyasashrama in 1593. He is historically significant as the primary motivator behind the documentation of the Svapnavrindavanakhyana, a foundational text revealed by Sri Vadiraja through the dreams of a deaf and dumb Brahmin. Under Vedanidhi Theertha’s guidance, these divine revelations were recorded by his pupil, Ramachandracharya, providing the world with an authoritative treatise on the spiritual essence and greatness of Sri Vadiraja and his Vrindavana. He further compiled the Anuvrindavanakhyana and installed a sacred stone inscription at Sode containing a pivotal verse revealed in a dream, which he established as an object of daily worship.

His tenure was marked by several miraculous events that solidified the spiritual prestige of the Sode Matha. When a massive stone pillar (Dhvajastambha) repeatedly failed to stand in front of the Trivikrama Temple, Vedanidhi Theertha successfully installed it only after inscribing the image of Sri Vadiraja in his Hamsarudha form, as directed in a vision. He also displayed supernatural authority by relocating a protective King Cobra from Madhyavata Matha to Sode, where the serpent’s presence is still recognized near the holy shrines. Vedanidhi Theertha conducted two biennial Paryayas in Udupi and is revered in the tradition as a divine soul destined to become the next Garuda. He entered his holy Vrindavana at Sode in 1648 CE after a 32-year tenure.');
INSERT INTO guru_parampara (id, name, order_index, ashrama_guru, ashrama_shishya, period, peetarohana, aaradhane, vrindavana_location, vrindavana_map_link, vrindavana_lat, vrindavana_long, ashrama_guru_id, ashrama_shishya_id, description) VALUES (24, 'Sri Varadaraja Theertha II', 24, 'Sri Vedanidhi Theertha', 'Sri Vishwadhiraja Theertha', '1648-1673 CE', 'c. 1648 CE', 'Data Unavailable', 'Theerthahalli', NULL, NULL, NULL, 23, 25, 'Sri Varadaraja Theertha was initiated into the ascetic order by Sri Vedanidhi Theertha and was highly regarded for his profound devotion to the presence of Sri Vadiraja. Throughout his tenure, he spent a significant portion of his time at the  Theerthahalli Matha, where he dedicated himself to the regular instruction of disciples through Patha-Pravachana (lectures and discourses). His scholarly contributions and commitment to the pedagogical traditions of the lineage ensured the continued intellectual growth of the Matha during the mid-17th century.

During his leadership, he successfully performed the biennial Paryaya at Udupi from 1660 to 1661, upholding the ritualistic standards of the Sri Krishna Temple. Sri Varadaraja Theertha presided over the tenure seat for twenty-five years, guiding the community with a balanced focus on academic rigor and meditative service. He entered his holy Vrindavana in 1673 CE at  Theerthahalli, leaving behind a legacy of dedicated scholarship and spiritual stability.');
INSERT INTO guru_parampara (id, name, order_index, ashrama_guru, ashrama_shishya, period, peetarohana, aaradhane, vrindavana_location, vrindavana_map_link, vrindavana_lat, vrindavana_long, ashrama_guru_id, ashrama_shishya_id, description) VALUES (25, 'Sri Vishwadhiraja Theertha', 25, 'Sri Varadaraja Theertha II', 'Sri Vadivandya Theertha', '1673-1688 CE', 'c. 1673 CE', 'Data Unavailable', 'Sode', 'https://maps.app.goo.gl/QVGRLSPLX9wtmfQt9', 14.734674684081776, 74.77885236443097, 24, 26, 'Sri Vishwadhiraja Theertha demonstrated a profound preference for the spiritual atmosphere of Sode, where he dedicated himself to the service of Sri Vadiraja’s feet. He viewed the regular conduct of Patha-Pravachana and the performance of religious rites as a moral duty, fulfilling his commitment to Siddhanta-seva with an exemplary spirit. Throughout his fifteen-year tenure, he maintained a rigorous balance between his personal meditative practices and his administrative responsibilities as the head of the Sode lineage.

Following the tradition of his predecessors, Sri Vishwadhiraja Theertha performed the biennial Paryaya at Udupi during the years 1676 and 1677. During this significant period, he focused heavily on the academic propagation of the Dvaita school, teaching the Sarvamula and other foundational works to a dedicated group of pupils. His intellectual dominance was further showcased when he organized a prestigious assembly of scholars, where he successfully defeated opponents through advanced theological debate. He entered his holy Vrindavana at Sode in 1688 CE, with his shrine situated adjacent to the Mruttika-vrindavana of Sri Vrindavanacharya.');
INSERT INTO guru_parampara (id, name, order_index, ashrama_guru, ashrama_shishya, period, peetarohana, aaradhane, vrindavana_location, vrindavana_map_link, vrindavana_lat, vrindavana_long, ashrama_guru_id, ashrama_shishya_id, description) VALUES (26, 'Sri Vadivandya Theertha', 26, 'Sri Vishwadhiraja Theertha', 'Sri Vishwavandya Theertha III', '1688-1706 CE', 'c. 1688 CE', 'Data Unavailable', 'Sode', 'https://maps.app.goo.gl/QVGRLSPLX9wtmfQt9', 14.734674684081776, 74.77885236443097, 25, 27, 'Sri Vadivandya Theertha was a distinguished scholar renowned for his profound expertise in the Nyayasudha and other foundational Vedantic works, which he taught extensively throughout his tenure. He is celebrated in the tradition for his intellectual defense of the Dvaita position, particularly during his biennial Paryaya in Udupi from 1692 to 1693. A hallmark of his scholarly career was his successful debate against the prominent Shaivadvaita scholar Shamashastry; during this exchange, Vadivandya Theertha systematically refuted the concept of Mithyatva (the illusory nature of the world), vindicating the Siddhanta on firm logical grounds.

Beyond his dialectical achievements, he contributed significantly to the devotional literature of the Matha through several extant works. Notable among these are the Sri Vadirajastuti, Sri Vadirajashtaka, Jayastotra, and Vadirajadhyanaprakara, which focus on the glorification and meditative visualization of Sri Vadiraja Theertha. He presided over the Sode lineage for eighteen years, guiding the community with scholarly rigor and administrative dedication. Sri Vadivandya Theertha entered his holy Vrindavana at Sode in 1706 CE, where his shrine is located adjacent to that of Sri Vedanidhi Theertha.');
INSERT INTO guru_parampara (id, name, order_index, ashrama_guru, ashrama_shishya, period, peetarohana, aaradhane, vrindavana_location, vrindavana_map_link, vrindavana_lat, vrindavana_long, ashrama_guru_id, ashrama_shishya_id, description) VALUES (27, 'Sri Vishwavandya Theertha III', 27, 'Sri Vadivandya Theertha', 'Sri Vibudhavarya Theertha', '1706-1722 CE', 'c. 1706 CE', 'Data Unavailable', 'Udupi', NULL, 13.3416944115392, 74.75298113858852, 26, 28, 'Sri Vishwavandya Theertha significantly enriched the spiritual lineage through his rigorous adherence to the duties of Sanyasashrama and his profound mastery of the Sarvamula corpus and the works of Sri Vadiraja. He was particularly known for his deep devotion at the Vrindavana of Sri Vadiraja in Sode, where he conducted numerous sessions of Patha-Pravachana (teaching) and Parayana (recitation) of the complex philosophical work, Yuktimallika. His intellectual reputation was such that even traveling scholars from North India were reportedly stunned by his comprehensive command over the various Shastras.

Beyond his Vedantic expertise, Sri Vishwavandya Theertha possessed an exceptional mastery of Purvamimamsa (hermeneutics) and Vyakarana (grammar). His scholarly legacy includes a rare and authoritative work on Mimamsa titled Bhattabodhini, a contribution specifically highlighted by the later pontiff Sri Vishwottama Theertha. He successfully performed his biennial Paryaya at Udupi during the years 1708 and 1709. After a sixteen-year tenure as the head of the Sode lineage, he entered his holy Vrindavana in 1722 CE His shrine is located in Udupi, situated directly behind that of Sri Vagisha Theertha.');
INSERT INTO guru_parampara (id, name, order_index, ashrama_guru, ashrama_shishya, period, peetarohana, aaradhane, vrindavana_location, vrindavana_map_link, vrindavana_lat, vrindavana_long, ashrama_guru_id, ashrama_shishya_id, description) VALUES (28, 'Sri Vibudhavarya Theertha', 28, 'Sri Vishwavandya Theertha III', 'Sri Vishwanidhi Theertha', '1722-1739 CE', 'c. 1722 CE', 'Margashirsha Krishna Shashti', 'Udupi', NULL, 14.734674684081776, 74.77885236443097, 27, 29, 'Sri Vibudhavarya Theertha was a distinguished saint-scholar who conducted the first complete renovation of the Sode Matha. A master of the Shastras, he taught the Nyayasudha eleven times and authored the Subhadraharana Mahakavya alongside a rare commentary on the Vishnusahasranama. His spiritual authority was famously tested when the King of Ikkeri, misled by a jealous local, seized the Matha’s treasures. After Sri Vibudhavarya Theertha retreated to Sode in fasting and prayer, the king suffered divine retribution and eventually sought forgiveness, returning the stolen goods which had miraculously turned to ash, except for the sacred sapphire of the Hayagriva icon.

In his final years, he intended to pen a commentary titled Vimalabodhini, but he ceased the work after a divine vision from Sri Vadiraja advised him to focus on meditation instead. He successfully performed the 1724–25 Krishna Paryaya in Udupi, maintaining the high ritualistic and academic standards of his lineage. After seventeen years of leadership, he entered his holy Vrindavana in 1739 CE, where his shrine remains a site of veneration in Udupi.');
INSERT INTO guru_parampara (id, name, order_index, ashrama_guru, ashrama_shishya, period, peetarohana, aaradhane, vrindavana_location, vrindavana_map_link, vrindavana_lat, vrindavana_long, ashrama_guru_id, ashrama_shishya_id, description) VALUES (29, 'Sri Vishwanidhi Theertha', 29, 'Sri Vibudhavarya Theertha', 'Sri Vishwadhishwara Theertha', '1739-1753 CE', 'c. 1739 CE', 'Data Unavailable', 'Undaru (Innanje)', NULL, NULL, NULL, 28, 30, 'Sri Vishwanidhi Theertha, the twenty-ninth pontiff in the lineage of Sri Vishnu Theertha, was a distinguished scholar and a dedicated preceptor who traveled extensively throughout Southern India to propagate the Dvaita Siddhanta. He was renowned for his extraordinary memory and intellectual command, particularly over the Srimad Bhagavata and the Nyayasudha, which he could recite and teach fluently without the aid of any written texts. His commitment to the academic development of his successor, Sri Vishwadhishwara Theertha, was so profound that he provided constant instruction even while on the move, ensuring his disciple achieved mastery over the Shastras.

During his biennial Paryaya at Udupi in 1740–1741, he delivered a monumental year-long discourse on the Bhagavata. His dialectical skills were equally impressive; he famously defeated Sridhara Sharma, a prominent Shrivaishnava scholar, in a scholarly debate centered on the concept of Bhakti. Under his leadership, the Matha’s prestige grew significantly, attracting numerous gifts and endowments from various royal families and devotees. Sri Vishwanidhi Theertha presided over the Sode lineage for fourteen years before entering his holy Vrindavana in 1753 CE His shrine is located in the serene village of Undaru (Innanje) in the Udupi district.');
INSERT INTO guru_parampara (id, name, order_index, ashrama_guru, ashrama_shishya, period, peetarohana, aaradhane, vrindavana_location, vrindavana_map_link, vrindavana_lat, vrindavana_long, ashrama_guru_id, ashrama_shishya_id, description) VALUES (30, 'Sri Vishwadhishwara Theertha', 30, 'Sri Vishwanidhi Theertha', 'Sri Vishwesha Theertha', '1753-1803 CE', 'c. 1753 CE', 'Pushya Shukla Trayodashi', 'Undaru (Innanje)', NULL, NULL, NULL, 29, 31, 'Sri Vishwadhishwara Theertha, known as the "Senior Swamiji," was a towering figure whose fifty-year tenure was defined by academic brilliance and spiritual prosperity. A master of the Srimad Bhagavata, Nyayasudha, and Yuktimallika, he famously conducted ten simultaneous Mangala ceremonies for these complex works. His leadership was marked by two grand biennial Paryayas and a deep commitment to the traditional singing customs of the Bhagavataru. In the Vrindavanakhyana, he is honored with the title "Vipraparama-guru" and is credited with providing vital guidance to the future saint, Sri Vrindavanacharya.

A hallmark of his influence was his encounter with Diwan Poornayya of Mysore. Through intuitive vision, the Swamiji identified a golden Mantapa the Diwan had prepared, eventually persuading him to gift the masterpiece to the Udupi Krishna Matha for the Lord’s service. This golden shrine remained a central feature of the temple’s worship for many decades. Sri Vishwadhishwara Theertha entered his holy Vrindavana in 1803 CE at Undaru, resting beside his preceptor, Sri Vishwanidhi Theertha.');
INSERT INTO guru_parampara (id, name, order_index, ashrama_guru, ashrama_shishya, period, peetarohana, aaradhane, vrindavana_location, vrindavana_map_link, vrindavana_lat, vrindavana_long, ashrama_guru_id, ashrama_shishya_id, description) VALUES (31, 'Sri Vishwesha Theertha', 31, 'Sri Vishwadhishwara Theertha', 'Sri Vishwapriya Theertha', 'Upto 1794 CE', 'Data Unavailable', 'Magha Krishna Trayodashi', 'Kenchagaru (Honnavara)', NULL, NULL, NULL, 30, 32, 'Sri Vishwesha Theertha, the thirty-first pontiff in the lineage, is the subject of a remarkable spiritual transformation. Initially perceived by his preceptor, Sri Vishwadhishwara Theertha, as lacking the necessary intellectual sharpness, he retreated to a secluded location to perform rigorous penance. Tradition holds that Goddess Saraswati, pleased by his devotion, appeared physically and wrote a sacred Bijakshara on his tongue, instantly granting him vast and profound knowledge. This divine intervention transformed him into a formidable scholar, leading him to dominate theological debates in North India and Kashi, where he was repeatedly honored with Jayapatras (certificates of victory).

Known popularly as the "Kenchagaru Swamiji," he was a figure of immense influence who even initiated King Ramavarma of Cochin into the Madhva fold. Despite his academic brilliance, which was compared to the fragrance of musk, he remained a devoted disciple, performing his biennial Paryaya in Udupi during 1788–1789 with his Guru’s permission. In the Vrindavanakhyana, he is referred to as "Vipraguru" or "Vitthala" (his birth name), and the text details his transition of spiritual responsibilities—specifically the Pacchotika or sacred case of deities—to his successor, Sri Vishwapriya Theertha.

Sri Vishwesha Theertha is said to have entered his holy Vrindavana in 1794 CE at Kenchagaru village near Honnavara, notably while his own Guru was still alive. His tenure, though marked by an early departure from the mortal world, left a legacy of intellectual excellence and royal patronage from the Keladi kings and other southern dynasties. His annual Aradhana is observed on the thirteenth day of the dark half of the month of Magha.');
INSERT INTO guru_parampara (id, name, order_index, ashrama_guru, ashrama_shishya, period, peetarohana, aaradhane, vrindavana_location, vrindavana_map_link, vrindavana_lat, vrindavana_long, ashrama_guru_id, ashrama_shishya_id, description) VALUES (32, 'Sri Vishwapriya Theertha', 32, 'Sri Vishwesha Theertha', 'Sri Vishwadhisha Theertha', '1774–1865 CE', 'c. 1794 CE', 'Data Unavailable', 'Udupi', NULL, NULL, NULL, 31, 33, 'Sri Vishwapriya Theertha, popularly revered as Vrindavanacharya, was a nineteenth-century mystic and a pivotal figure in the Sode Matha lineage. Initiated at age ten by Sri Vishwesha Theertha, he sought higher knowledge at Sode, where he performed rigorous penance and received direct instruction from the divine speech of Sri Vadiraja Theertha. Tradition identifies him as the reincarnation of the "deaf and dumb Brahmin" who originally heard the Vrindavanakhyana in a dream; consequently, he became the authority (Harikara) in spreading its greatness.

Vrindavanacharya’s 62-year tenure was marked by four glorious biennial Paryayas in Udupi. Despite receiving royal honors—including an emerald Mantapa from Mummadi Krishnaraja Wodeyar—he maintained extreme Vairagya (detachment), famously appearing even in royal durbars wearing only a loincloth. His intellectual mastery was matchless; he taught hundreds of scholars and commissioned foundational commentaries on the Akhyana.

His life was replete with miracles: he saved a drowning devotee in the Kaveri, turned ocean water sweet at Rameswaram for Achamana, and increased food quantities through sacred words. He also reconfirmed the Samatva worship of Vadiraja with Lord Vayu. Entering Vrindavana in 1865 at age 91, his shrine in Udupi features a carved Brahmin figure, signifying his past identity. Tradition acclaims him as the divine soul destined to become Indra in the next Kalpa.');
INSERT INTO guru_parampara (id, name, order_index, ashrama_guru, ashrama_shishya, period, peetarohana, aaradhane, vrindavana_location, vrindavana_map_link, vrindavana_lat, vrindavana_long, ashrama_guru_id, ashrama_shishya_id, description) VALUES (33, 'Sri Vishwadhisha Theertha', 33, 'Sri Vishwapriya Theertha', 'Sri Vishwendra Theertha', 'Late 19th Cent.', 'c. 1865 CE', 'Ashadha Amavasya', 'Udupi', NULL, NULL, NULL, 32, 34, 'Sri Vishwadhisha Theertha, the successor to Vrindavanacharya, was a physically imposing and intellectually dominant figure known as Hiriya Swamigalu (Senior Swamiji). He attained mastery over the Shastras through rigorous study under Sri Vidyadhisha Theertha of Krishnapur Matha and a dedicated one-Mandala recitation of the Samgraha Ramayana at the shrine of Lord Mukhyaprana in Udupi. His erudition was so profound that he served as a preceptor to numerous contemporary pontiffs, including the heads of the Adamaru, Kaniyuru, and Krishnapur Mathas.

Swamiji’s tenure was defined by his fierce defense of the Siddhanta. When the Rujutva status of Sri Vadiraja was challenged at a convention in Madras in 1884, he swiftly countered by organizing a mass meeting in Udupi and publishing the seminal work Rujutvachandrodaya. This book became a foundational authority for establishing the divine status of Sri Vadiraja. His academic excellence earned him international recognition, including a formal letter of praise from Queen Victoria, which remains a preserved document at the Sode Matha.

During his 34-year leadership, he performed two biennial Paryayas (1868–69 and 1884–85) and oversaw significant renovations within the inner shrine of the Sri Krishna Temple. Sri Vishwadhisha Theertha entered his holy Vrindavana in 1889 CE at Udupi, located directly behind the shrine of his Guru. Such was his impact that a local holiday was declared on the day of his passing.');
INSERT INTO guru_parampara (id, name, order_index, ashrama_guru, ashrama_shishya, period, peetarohana, aaradhane, vrindavana_location, vrindavana_map_link, vrindavana_lat, vrindavana_long, ashrama_guru_id, ashrama_shishya_id, description) VALUES (34, 'Sri Vishwendra Theertha', 34, 'Sri Vishwadhisha Theertha', 'Sri Vishwottama Theertha', '1889–1943 CE', 'c. 1900 CE', 'Ashwayuja Shukla Navami', 'Udyavara (Udupi)', NULL, NULL, NULL, 33, 35, 'Sri Vishwendra Theertha (1881–1943) was a multifaceted nineteenth-century pontiff whose 44-year tenure blended profound Shastric scholarship with progressive social vision. Initiated at age 16, he mastered Veda-Vedanta under Sri Vibudhapriya Theertha of Adamar Matha. He was a prolific literary figure, composing Kannada poetry under the pen name "Rajesh-Rajanath" and authoring the Sanskrit Sri Vadirajashtaka. His ritualistic life was exemplary; he was known for an elaborate, unwavering style of daily worship that strictly incorporated traditional mantra chanting and devotional singing.

A pioneer in modern education, Swamiji established the Vishnumurthy Hayavadanaswamy High School in Innanje—the first such institution in the region—which has since flourished into a leading Pre-University College. His intellectual leadership was further cemented through the organization of the "Yuktimallika Sourabha Prakashini", a long-running scholarly assembly held at the Sri Ananteshwara Temple to promote the works of Sri Vadiraja.

During his three successful biennial Paryayas, he renovated the Vrindavanashala in Udupi. He enjoyed significant royal patronage, receiving honors and substantial grants for the Krishna Matha from King Ramavarma of Cochin and Maharaja Krishnarajendra Wodeyar of Mysore. Remarkably, he was also an expert Ayurvedic physician who formulated "Hayagrivataila", a medicated oil for rheumatic pain that remains a signature preparation of the Sode Matha today. Sri Vishwendra Theertha entered his holy Vrindavana in 1943 at Udyavara, leaving a legacy of academic patronage, medical service, and educational reform.');
INSERT INTO guru_parampara (id, name, order_index, ashrama_guru, ashrama_shishya, period, peetarohana, aaradhane, vrindavana_location, vrindavana_map_link, vrindavana_lat, vrindavana_long, ashrama_guru_id, ashrama_shishya_id, description) VALUES (35, 'Sri Vishwottama Theertha', 35, 'Sri Vishwendra Theertha', 'Sri Vishwavallabha Theertha', '1934–2007 CE', '1943 CE', 'Naga Panchami', 'Sode', 'https://maps.app.goo.gl/QVGRLSPLX9wtmfQt9', 14.734674684081776, 74.77885236443097, 34, 36, 'Sri Vishwottama Theertha (1934–2007) was a towering 20th-century pontiff characterized by a rare synthesis of rigorous self-discipline and profound Shastric scholarship. Born in Udyavara as Madhava, he displayed an early inclination toward meditation and solitude, leading his predecessor, Sri Vishwendra Theertha, to nominate him as successor. Starting his tenure in 1943 at the age of nine, he shouldered the responsibilities of the Matha for 64 years. He pursued higher Vedantic studies under Sri Vidyasamudra Theertha of Kaniyoor Matha, emerging as a sage-scholar who remained humble and detached from public acclaim despite his vast intellectual depth.

His administrative and spiritual legacy is immense. He performed four biennial Paryayas in Udupi (1948–1997), during which he organized the 500th birth anniversary of Sri Vadiraja and constructed the Vadiraja Mandira near the Krishna Temple. At Sode, which he considered his ultimate sanctuary, he executed historical renovations, established the Bhavisameera Gurukula, and fulfilled a divine instruction by having the entire Vrindavanakhyana inscribed in stone within the newly built Akhyanamandira. An ardent researcher, he personally collected over two thousand rare manuscripts, preserving them for future generations of scholars.

Beyond the Shastras, Sri Vishwottama Theertha was a compassionate social reformer. He upgraded the educational facilities at Innanje to a Pre-University College and established a large-scale Goshala at Huvinakere to protect aged cows. Known for his "serene light" and healing Mantrakshata, he served as a spiritual refuge for thousands. He peacefully departed the mortal world in 2007 while uttering the name of Rama, having lived a life of total surrender to Lord Hayagriva and Sri Vadiraja.');
INSERT INTO guru_parampara (id, name, order_index, ashrama_guru, ashrama_shishya, period, peetarohana, aaradhane, vrindavana_location, vrindavana_map_link, vrindavana_lat, vrindavana_long, ashrama_guru_id, ashrama_shishya_id, description) VALUES (36, 'Sri Vishwavallabha Theertha', 36, 'Sri Vishwottama Theertha', 'Incumbent', '2007–Present', '2007 CE', 'Living', 'N/A', NULL, NULL, NULL, 35, NULL, 'Sri Vishwavallabha Theertha, born Raghava in 1991, is the current pontiff of the Sode Vadiraja Matha. Grandson of the renowned Vidwan Sri Gururaj Tantri, his extraordinary spiritual future was predicted at birth. He embraced Sanyasashrama in 2006 under Sri Vishwottama Theertha, subsequently undertaking rigorous Shastric studies. Since assuming administrative responsibility, he has balanced traditional preservation with modern social service.

A visionary leader, Swamiji initiated the construction of Rajadhama at Sode and established the Srimadvrindavanacharya Samshodhana hagu Prakashana Kendra to preserve and publish thousands of ancient manuscripts. To support contemporary scholars, he launched the Vidwatsambhavane scheme and the religious magazine Tattvamallika. Extending the Matha’s educational legacy, he founded the Shri Madhva Vadiraja Institute of Technology and Management (SMVITM) to provide high-quality technical education to rural students.

His first biennial Paryaya (2012–2014) was historic, featuring the commissioning of a new Brahmaratha for Lord Krishna and the publication of Vadiraja’s Yuktimallika in ten comprehensive volumes. He also oversaw the translation of the Mahabharatha Tatparya Nirnaya with Vadiraja’s commentary. Known for his Vaksiddhi and deep devotion to the Rujutva of Sri Vadiraja, he continues to lead the Matha with a focus on Annadana, scholarly discourses, and social welfare programs, including aid for the underprivileged and medical support.');

-- Seva Catalog Data
DELETE FROM seva_bookings;
DELETE FROM sevas;
INSERT INTO sevas (id, title_english, title_kannada, amount, description, category, is_active) VALUES (gen_random_uuid(), 'One Day Full Seva (including Annadana)', 'ಒಂದು ದಿನದ ಸಂಪೂರ್ಣ ಸೇವೆ (ಅನ್ನದಾನ ಸಹಿತ)', 5001, NULL, 'SODE', true);
INSERT INTO sevas (id, title_english, title_kannada, amount, description, category, is_active) VALUES (gen_random_uuid(), 'Maha Sarvaseva (including special Night Pooja of Bhutaraja)', 'ಮಹಾ ಸರ್ವಸೇವಾ (ರಾತ್ರಿ ವಿಶೇಷ ಭೂತರಾಜರ ಪೂಜಾ ಸಹಿತ)', 1500, NULL, 'SODE', true);
INSERT INTO sevas (id, title_english, title_kannada, amount, description, category, is_active) VALUES (gen_random_uuid(), 'Tulasi Archana (to Sri Trivikrama Devaru)', 'ತುಳಸಿ ಅರ್ಚನೆ (ಶ್ರೀ ತ್ರಿವಿಕ್ರಮ ದೇವರಿಗೆ)', 25, NULL, 'SODE', true);
INSERT INTO sevas (id, title_english, title_kannada, amount, description, category, is_active) VALUES (gen_random_uuid(), 'Pratyaksha Godana (Uttama Kalpa)', 'ಪ್ರತ್ಯಕ್ಷ ಗೋದಾನ (ಉತ್ತಮ)', 25000, NULL, 'SODE', true);
INSERT INTO sevas (id, title_english, title_kannada, amount, description, category, is_active) VALUES (gen_random_uuid(), 'Pratyaksha Godana (Madhyama Kalpa)', 'ಪ್ರತ್ಯಕ್ಷ ಗೋದಾನ (ಮಧ್ಯಮ)', 15000, NULL, 'SODE', true);
INSERT INTO sevas (id, title_english, title_kannada, amount, description, category, is_active) VALUES (gen_random_uuid(), 'Godana (excluding Dakshine)', 'ಗೋದಾನ (ದಕ್ಷಿಣೆ ಹೊರತು)', 3000, NULL, 'SODE', true);
INSERT INTO sevas (id, title_english, title_kannada, amount, description, category, is_active) VALUES (gen_random_uuid(), 'Nandadeepa (for 1 Year)', 'ನಂದಾದೀಪ (ಒಂದು ವರ್ಷದ)', 1200, NULL, 'SODE', true);
INSERT INTO sevas (id, title_english, title_kannada, amount, description, category, is_active) VALUES (gen_random_uuid(), 'Nandadeepa (for 1 Month)', 'ನಂದಾದೀಪ (ಒಂದು ತಿಂಗಳದ)', 100, NULL, 'SODE', true);
INSERT INTO sevas (id, title_english, title_kannada, amount, description, category, is_active) VALUES (gen_random_uuid(), 'Sri Bhutarajara Special Night Pooja', 'ಶ್ರೀ ಭೂತರಾಜರ ವಿಶೇಷ ರಾತ್ರಿ ಪೂಜಾ', 101, NULL, 'SODE', true);
INSERT INTO sevas (id, title_english, title_kannada, amount, description, category, is_active) VALUES (gen_random_uuid(), 'Thulabhara (Items and Dakshine separate)', 'ತುಲಾಭಾರ (ಸಾಮ್ಯ ರಹಿತ ಮತ್ತು ದಕ್ಷಿಣೆ ಪ್ರತ್ಯೇಕ)', 100, NULL, 'SODE', true);
INSERT INTO sevas (id, title_english, title_kannada, amount, description, category, is_active) VALUES (gen_random_uuid(), 'Kumkumarchana (to Rama Devi)', 'ಕುಂಕುಮಾರ್ಚನೆ (ರಮಾ ದೇವಿಗೆ)', 10, NULL, 'SODE', true);

-- Branch Dictionary Data
DELETE FROM branches;
INSERT INTO branches (id, name, address, city, state, pincode, phone, map_link, latitude, longitude) VALUES (gen_random_uuid(), 'Sri Sode Vadiraja Matha, Udupi', 'Carstreet, Udupi', 'Udupi', 'Karnataka', '576101', '+91 820 2524004', 'https://maps.google.com/?q=13.340361,74.752752', 13.340361, 74.752752);
INSERT INTO branches (id, name, address, city, state, pincode, phone, map_link, latitude, longitude) VALUES (gen_random_uuid(), 'Sri Sode Vadiraja Matha, Sonda', 'Sonda, Sirsi Taluk', 'Sonda', 'Karnataka', '581336', '+91 9483357005, +91 8277123333', 'https://maps.google.com/?q=14.734226,74.778358', 14.734226, 74.778358);
INSERT INTO branches (id, name, address, city, state, pincode, phone, map_link, latitude, longitude) VALUES (gen_random_uuid(), 'Sri Sode Vadiraja Matha, Gokarna', 'Gokarna', 'Gokarna', 'Karnataka', '581326', '9449640074, 08386-257859', 'https://maps.google.com/?q=14.541164,74.320080', 14.541164, 74.320080);
INSERT INTO branches (id, name, address, city, state, pincode, phone, map_link, latitude, longitude) VALUES (gen_random_uuid(), 'Sri Sode Vadiraja Matha, Kumbhasi', 'Kumbhasi', 'Kumbhasi', 'Karnataka', '576257', '9141348548', 'https://maps.google.com/?q=13.568916,74.702364', 13.568916, 74.702364);
INSERT INTO branches (id, name, address, city, state, pincode, phone, map_link, latitude, longitude) VALUES (gen_random_uuid(), 'Sri Kamadhenu Gosamrakshana Trust', 'Hoovinakere', 'Hoovinakere', 'Karnataka', '576257', '8431273542', 'https://maps.google.com/?q=13.572084,74.732373', 13.572084, 74.732373);
INSERT INTO branches (id, name, address, city, state, pincode, phone, map_link, latitude, longitude) VALUES (gen_random_uuid(), 'Sri Sode Vadiraja Matha, Renjala', 'Renjala', 'Renjala', 'Karnataka', '574113', '9902199431', 'https://maps.google.com/?q=13.1528,75.0670', 13.1528, 75.0670);
INSERT INTO branches (id, name, address, city, state, pincode, phone, map_link, latitude, longitude) VALUES (gen_random_uuid(), 'Madhyavata Matha, Naddantadi', 'Naddantadi', 'Naddantadi', 'Karnataka', '574211', '+91 9448939795', 'https://maps.google.com/?q=12.960536,75.125304', 12.960536, 75.125304);
INSERT INTO branches (id, name, address, city, state, pincode, phone, map_link, latitude, longitude) VALUES (gen_random_uuid(), 'Sri Sode Vadiraja Matha, Narala', 'Narala', 'Narala', 'Karnataka', '574144', '+91 9449936717', 'https://maps.google.com/?q=12.9617813,74.9608061', 12.9617813, 74.9608061);
INSERT INTO branches (id, name, address, city, state, pincode, phone, map_link, latitude, longitude) VALUES (gen_random_uuid(), 'Hanuman temple, Nadavaramba', 'Nadavaramba', 'Thrissur', 'Kerala', '680661', '+91 9844753084', 'https://maps.google.com/?q=10.5276,76.2144', 10.5276, 76.2144);
INSERT INTO branches (id, name, address, city, state, pincode, phone, map_link, latitude, longitude) VALUES (gen_random_uuid(), 'Sri Sode Vadiraja Matha, Chennai', 'T Nagara', 'Chennai', 'Tamil Nadu', '600017', '09092946633', 'https://maps.google.com/?q=13.0405,80.2337', 13.0405, 80.2337);

-- Admin User
DELETE FROM users WHERE phone_number = '7259202884';
INSERT INTO users (id, phone_number, full_name, email, role, is_admin, is_volunteer, volunteer_request, created_at, consent_data_storage, consent_communications)
VALUES (gen_random_uuid(), '7259202884', 'Admin User', 'admin@sodematha.in', 'ADMIN', true, false, false, NOW(), true, true);
